### ISSUE TITLE
Add a 'Following' Tab on the Home Page

### ISSUE THREAD

**Issue by blakee-marcus** [blakee-marcus/deep-thoughts#10]
# Description:

In our MERN stack application, we've observed a need to better tailor the user experience on the homepage regarding the post feeds they see.

# Requirements:

1. **Update Apollo Queries:**
 - The Apollo query on the backend should be updated such that it fetches posts from users that the logged-in user is following.
 - The posts should be sorted from the newest to oldest based on their post date.  

2.  **Homepage Tabs for Logged-in Users:**
- If the user is logged in, introduce two new tabs at the top of the homepage. These tabs should be placed between existing tabs 'for you' and 'following.'
   - **For You Tab:** When selected, this tab should:
Display all posts irrespective of whom the logged-in user follows.
  - **Following Tab:** When selected, this tab should:
Display all the posts from users that the logged-in user follows.
List the posts from newest to oldest based on post date.  

# Steps to Reproduce (For Testing):

1. Log in to the application.
2. Navigate to the homepage.
3. Observe the two new tabs between 'for you' and 'following.'
4. Click on the 'For You' tab and verify posts from followed users are displayed in the newest to oldest order.
5. Click on the 'Following' tab and verify that it displays all posts.  

# Expected Outcome:
Posts should load accordingly based on the selected tab and Apollo query results. Proper sorting and filtering mechanisms should be in place to ensure the user sees the desired content.

**Comment by Krishcode264** [comment]
are you still working on it ?

**Comment by blakee-marcus** [comment]
I am! I updated the backend to query 'thoughts' from followed users with the newest 'thoughts' at the top.
